- README.md
- examples/telegraf.conf.d/postgres.conf
- manifests/init.pp
- manifests/profile/dashboards.pp
- manifests/profile/postgres_access.pp
- manifests/telegraf/agent.pp
- manifests/telegraf/config.pp
Also, don't include the postgres access class in the telegraf manifest,
since this needs to be present in the catalog of the postgres nodes
> Add README

- metadata.json
Prior to this commit the metadata had the wrong module URL which led to the incorrect changelog being generated
> correction of module url in metadata

- README.md
- manifests/init.pp
- manifests/profile/dashboards.pp
- manifests/telegraf/agent.pp
- metadata.json
This commit changes the use of influxdb::retrieve_token to be a Deferred
function.  This allows agents to retrieve a token during catalog
application, which in turn removes the need to set influxdb::token after
the first catalog application.
> Use retrieve_token as a Deferred function

- examples/telegraf.conf.d/postgres.conf
- examples/telegraf.conf.d/puppetdb.conf
Prior to this commit, the error checking was too aggressive and resulted
in emitting no metrics from PDB json files.  This is because the 'error'
object is always in the result and we need to check the length of its
values.
> Fix handling of 'error' entry in dict

- files/datasource.epp
Prior to this commit, $token was declared as a Sensitive[String], but we
may recieve an Undef value if the token was created in the current
catalog application.  This commit accepts any Sensitive value to account
for this.
> (SUP-3201) Accept any Sensitive value in template

- manifests/profile/postgres_access.pp
Prior to this commit, we did not create a postgres role for telegraf or
grant it any permissions.  This add two pe_postgresql_psql resources to
accomplish this.
> (SUP-3209) Grant pg_monitor role to telegraf

- manifests/profile/dashboards.pp
- templates/grafana_wait.epp
Prior to this commit, we used an exec resource to check if the grafana
service were ready to receive connections.  However, this didn't account
for initial provisioning, and it's a bit of a hack.  This commit uses an
ExecStartPost directive instead, which is better because it allows us to
use metaparameters like 'require' directly on the service.
> (SUP-3201) Check port availability with systemd

- manifests/telegraf/agent.pp
encompassing #34 this commit Bumps the telegraf version to the minimum version provided by Ubuntu 20.04
This also adds a missing require to the following file resource:
`file { '/etc/systemd/system/telegraf.service.d':`
This now correctly requires the telegraf class which resolves a resource ordering issue associated with ubuntu
> (SUP-3228) Fix Ubuntu compatibility issue

- manifests/telegraf/agent.pp
Prior to this commit, it was possible to end up in a cyclic dependency chain on the dashboard node.
This commit adds in specific chaining where none existed and changes the class statements to be more specific to the installing class rather than the top level.
> make resource ordering specific to install class

- .puppet-lint.rc
- .sync.yml
- README.md
- REFERENCE.md
- functions/hosts_with_profile.pp
- manifests/enterprise_infrastructure.pp
- manifests/telegraf/agent.pp
- metadata.json
- spec/acceptance/init_spec.rb
- spec/classes/enterprise_infrastructure_spec.rb
- spec/default_facts.yml
- spec/spec_helper_acceptance_local.rb
Prior to this commit, it was necessary to manually apply the toml-rb gem to compiling nodes, and apply the postgres_access class to database nodes.
This commit adds puppet_operational_dashboards::enterprise_infrastructure which when applied to the puppet infrastructure node group, automatically selects and applies appropriate prerequisites.
Marked as "backward-incompatible" as this is likely a change that warrants a 1.0 release when rolled up with all other recent changes
> (SUP-3061) Install class for ent infrastructure agents

- .puppet-lint.rc
- .sync.yml
- README.md
- Rakefile
- manifests/telegraf/agent.pp
Prior to this commit, Ubuntu provisioning would fail if the latest
telegraf package were newer than the $version parameter.  This looks to
be because only the latest package is available in the Ubuntu repo.
This commit changes the ensure property to be 'latest' on Ubuntu, and
changes the archive url to use the $version parameter.
> (SUP-3235) Use latest telegraf package on Ubuntu

- files/Postgresql_performance.json
- files/Puppetdb_performance.json
- files/Puppetserver_performance.json
- templates/puppetdb_jvm_metrics.epp
This commit also fixes an issue with the queue_depth metrics, which
comes from the /v1/status endpoint.
> Add panels for PDB read and write pools

- files/Puppetserver_performance.json
This commit changes these two panels to group by the name of the
function and http-client metric, thereby displaying all of them.  The
function counts now also use non_negative_difference over the time
interval, since this is a cumulative total.
> Display all http client and function metrics

- README.md
This commit adds in the descriptions of the default dashboards that was recently added to puppet_metrics_dashboards.
> (SUP-3241) Add in Dashboard documentation

- files/Puppetdb_performance.json
These panels had a few copy/paste mistakes, most notable the PDB active
write pool active connections was actually a duplicate of active read
connections.
> Fix panels related to PDB connections

- examples/telegraf.conf.d/puppetdb.conf
Prior to this commit, this metric was not being emitted from archive
metrics because I had confused jetty's queueSize metric with PDB's
queue_depth.  This commit emits the correct metric for the dashboard to
pick up.
> Fix queue_depth metric in starlark processor

- examples/telegraf.conf.d/puppetdb.conf
- files/Puppetdb_performance.json
This commits adds panels for PDB JVM garbage collection, not to be
confused with the panels we already have for PDB GC.  I renamed those to
hopefully avoid confusion.
> Add PDB JVM GC panels

- files/Puppetserver_performance.json
This commit adds two panels for route-id mean duration and counts.
> Add metrics from route-ids

- manifests/profile/dashboards.pp
Prior to this commit, the provisioning datasource file had a 'before'
metaparam on the Grafana service, which caused the service not to
refresh when the file changes.  This commit fixes this by changing the
'before' to a 'notify'.  The 'require' on the Grafana install class
still ensures proper ordering.
> (SUP-3319) Refresh service when datasource changes

- ARCHIVES.md
- README.md
This commit moves the section on importing archive metrics to its own
file and adds more detail about the process.
> (SUP-3329) Add metric archive info to ARCHIVES.md

- manifests/telegraf/agent.pp
- spec/default_facts.yml
This commit fixes a couple of issues related to Telegraf ssl
configuration.
* The service may have been started before the files were copied to
/etc/telegraf
* Changing this configuration did not refresh the Telegraf service
* The configuration didn't take the $use_ssl parameter into account
> (SUP-3348) Telegraf ssl bugfixes

- manifests/init.pp
- manifests/profile/dashboards.pp
- manifests/telegraf/agent.pp
- manifests/telegraf/config.pp
This commit fixes a few issues with this parameter, namely
* Not passing it to the 'influxdb' class
* Defaulting to 'https' in some classes and defined types
> (SUP-3358) Fix $use_ssl logic across all manifests

- README.md
- spec/acceptance/init_spec.rb
This commit documents the insserv-compat as a dependency for openSUSE
15.  It also installs it in the acceptance tests.
> (SUP-3349) Document SLES package requirement

- manifests/init.pp
- manifests/profile/dashboards.pp
Prior to this commit, the $manage_grafana parameter was present but
unused in the main class.  This commit moves it to the dashboard profile
class, the only place it is used.
> (SUP-3357) Move manage_grafana to dashboard class

- files/Puppetserver_performance.json
Prior to this commit, this panel didn't have the correct field aliases,
probably to do with selecting multiple fields in a single query.  This
commit splits it into two queries with the correct aliases.
> (SUP-3403) Fix labels in compile/borrow panel

- examples/telegraf.conf.d/postgres.conf
This commit adds index and toast metrics to be emitted by the postgres
starlark script.  It also fixes a small discrepency between the fields
emitted by the script and those expected by the dashboard
> (SUP-3431) Add index and toast stats to postgres

- manifests/profile/dashboards.pp
- spec/classes/dashboards_spec.rb
went to latest in 8.x stream as 9.x stream may require dev effort
https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
> (SUP-3646) Grafana Bump for security vulnerability

- spec/classes/dashboards_spec.rb
- templates/grafana_wait.epp
This flag to remove the header may not be available on all versions of ss, so use sed to delete it instead.
> (SUP-3675) Remove -H flag from ss command

- README.md
- manifests/telegraf/agent.pp
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/init_spec.rb
This commit adds support for installing Telegraf from an archive source
on Enterprise Linux variants.
> (SUP-3565) Support Telegraf archive install on EL

- files/plan_files/import_archives.sh
- plans/load_metrics.pp
This option ends up being faster than uploading the metrics directory specifically, as Bolt is faster at uploading a single file rather than many small files.
> Accept a support script tarball for archive metrics ingest

- manifests/telegraf/agent.pp
for [Telegraf agent: Add option to verify ssl certs](https://github.com/puppetlabs/puppet_operational_dashboards/issues/99)
> added insecure_skip_verify param

- files/Filesync_performance.json
- files/Postgresql_performance.json
- files/Puppetdb_performance.json
- files/Puppetserver_performance.json
Prior to this commit the dashboards where static until refreshed manually in the UI.
The new default behaviour for all dashboards, other than the system data dashboard (because its static data) is to autorefresh, _defaulting to the number 1 option, which in this case is 5(s)_
changed to 5m
> (SUP-3735) have dashboards autorefresh

- README.md
Prior to this commit, we said to use grafana::install_method to change the installation method.  However, we have a parameter puppet_operational_dashboards::profile::dashboards::grafana_install that determines this, so it should be used instead.
> Correct grafana_install method in airgap example

- manifests/telegraf/agent.pp
When using hosts retrieved from PuppetDB the order can change run to run. This change sorts the hosts so that the Telegraf configs maintain a consistent order across Puppet runs.
> Ensure consistent config generation order

- files/Filesync_performance.json
This change:
- Removes a duplicate metric query from the File-sync client timing graph
- Removes a file-sync-client metric which appears to have been mistakenly included in the File-sync storage graph
- Fixes the field name references in the File-sync client metrics to match the field names in Influx
> Filesync dashboard cleanup

- files/Filesync_performance.json
Commit 94a351c3 corrected the file sync client field names to match those stored in InfluxDB.  However, it also changed the JRuby lock and wait times, which is incorrect because those fields don't come from the file sync client metrics.  They are part of the 'jruby-metrics' object, so this commit changes them back to match.
> Fix JRuby lock wait and held times

- files/Postgresql_performance.json
Prior to this commit, we used the magic $__interval for the total db sizes in the postgres dashboard.  But, since this uses a sum() of multiple "total" columns, the data was skewed when changing the interval in the graph.  This commit uses 5m since that is the default interval for the metrics collector, and the panel should work for any interval
5m or longer.
> Group the total db size by 5m intervals

- files/Filesync_performance.json
- files/Postgresql_performance.json
- files/Puppetdb_performance.json
- files/Puppetserver_performance.json
- files/plan_files/postgres.conf
- files/plan_files/puppetserver.conf
This commit adds a dropdown for applying a group_by interval to all the
panels.  The default is 5 minutes to match the interval from the metrics
collector.  This makes it much easier to change the group_by, e.g. to 30
minutes to match the Puppet runinterval, or a custom collection
frequency.
> (SUP-4065) Add parameter for group_by interval

- .sync.yml
- files/Filesync_performance.json
- files/Orchestrator_performance.json
- files/plan_files/orchestrator.conf
- files/plan_files/puppetserver.conf
- manifests/init.pp
- manifests/profile/dashboards.pp
- manifests/telegraf/agent.pp
- manifests/telegraf/config.pp
- plans/load_metrics.pp
- spec/classes/agent_spec.rb
- spec/classes/dashboards_spec.rb
- spec/classes/init_spec.rb
- spec/default_facts.yml
- templates/orchestrator_metrics.epp
This commit adds a Grafana dashboard and Telegraf config for gathering and displaying Orchestrator metrics in PE.  It also adds its file sync client metrics to the Filesync dashboard, as well as file sync storage metrics for Puppet server
> (SUP-4087) Add Orchestrator metrics

- metadata.json
A new version of this module was released to add Puppet 8 support, so bump the dependency in this module to account for it.
> Bump dependency for inifile

- files/System_v2_performance.json
- files/plan_files/sar.conf
- manifests/profile/dashboards.pp
- plans/load_metrics.pp
- spec/classes/dashboards_spec.rb
Version 7 of the metrics collector introduced a new format for system_cpu metrics, which it repurposes for all sar related metrics. This commit adds a dashboard for it, an option for which version of the dashboard to manage, and an import script for the new metrics.
> Add dashboard and script for v2 system metrics

- files/Postgresql_performance.json
Prior to this commit, there was a default field selected for this panel that made it not show up unless manually changed.
> Remove selection override from db sizes panel

- REFERENCE.md
- manifests/telegraf/agent.pp
- spec/classes/agent_spec.rb
also includes https://github.com/puppetlabs/puppet_operational_dashboards/pull/178
> (#74) collect local PCP metrics

- files/Puppetserver_performance.json
This commit adds a state timeline panel for operations performed as part of catalog compilations.  It also replaces the "Function Performance" panel with a state timeline.
Lastly, we removed the "Function Counts" panel.  The reason is that this data is based on the "top 50" functions as determined by the aggregate metric. This often creates large gaps in the graph and is largely useless.  See https://tickets.puppetlabs.com/browse/TK-468
> Add state timelines for catalog and function perf

- metadata.json
Starting with puppet/telegraf 5 the toml-rb gem isn't required anymore. This requires puppetlabs/stdib 9.
> puppet/telegraf: Require 5.x; puppetlabs/stdib: Require 9.x 

- manifests/profile/dashboards.pp
- metadata.json
Removed Debian block from Dashboards.pp and changed version of grafana within metadata.json file, upping it from `3.0.0 to 3.0.1`
> (SUP-4436) Grafana Module Version Change

- README.md
When reviewing the documentation for a tutorial session, it was identified that the documentation was lacking access information for the Grafana dashboard. This PR includes an updated section in the Read-me for that access.
> (SUP-4478) Addition of access details for Grafana Dashboard

- README.md
Prior to this commit, installing Grafana from an archive source was listed as a supported method; however, this is currently non-functional and none of the acceptance tests use this method.  Attempting to do so will result in errors related to provisioned datasources, as well as not starting grafana-server correctly.  This commit removes mentions of Grafana archives from the README.
> (SUP-4225) Deprecate Grafana archive installations

- REFERENCE.md
- manifests/enterprise_infrastructure.pp
- manifests/init.pp
- manifests/profile/dashboards.pp
- manifests/telegraf/agent.pp
puppet-strings will pickup the default value from the code, we don't need to duplicate the information.
> Cleanup puppet-strings documentation

- .gitignore
- .pdkignore
- .rubocop.yml
- .sync.yml
- Gemfile
- README.md
- Rakefile
- manifests/profile/foss_postgres_access.pp
- manifests/telegraf/agent.pp
- metadata.json
- spec/classes/agent_spec.rb
- spec/classes/foss_postgres_spec.rb
- spec/classes/postgres_access_spec.rb
- spec/default_facts.yml
- templates/postgres.epp
This commit fixes postgres metrics on FOSS by:
* Choosing the appropriate database, 'puppet' or 'pe-puppet'
* Adding a new profile class to set up postgres auth
* Making the postgres connection string more configurable
> Fix collection of postgres metrics on FOSS Puppet

- manifests/init.pp
This commit updates the $include_pe_metrics to use a selector instead of a regex.  This prevents an error when the $settings::module_groups evaluates to nil, such as when using `puppet apply`.
> Fix logic to include pe metrics

- .sync.yml
- Rakefile
This commit tells the PDK to not manage the Rakefile in this module. The previous commit overwrote our changelog related config, which is also added back in this commit.
> Don't manage Rakefile with pdk

- files/datasource.epp
Currently empty buckets are being kept on the system. These can be removed via swagger API or UI if the editable: true property is added to this epp file
> Change to datasource to allow editable so buckets can be deleted
